import type { Character } from './types'

export const CHARACTERS: Character[] = [
  {
    id: 'alina',
    name: 'Алина',
    age: 22,
    blurb: 'Студентка с подработкой и голодом к росту.',
    difficulty: 'easy',
    cash: 42000,
    timePerMonth: 225,
    jobTitle: 'Бариста',
    careerLevel: 1,
    salary: 28000,
    jobHours: 90,
    field: 'Сервис',
    eduField: 'humanities',
    eduLevel: 1,
    proSkills: 0,
    network: 1,
    expenses: 18000,
    familySize: 0,
    habits: [{ id: 'net', name: 'Соцсети', monthlyCost: 0, monthlyTime: 12 }],
    hasCar: false,
    dreamOptions: ['studio', 'worldtrip', 'farm'],
  },
  {
    id: 'igor',
    name: 'Игорь',
    age: 34,
    blurb: 'Учитель со стабильным окладом.',
    difficulty: 'easy',
    cash: 140000,
    timePerMonth: 225,
    jobTitle: 'Учитель',
    careerLevel: 2,
    salary: 52000,
    jobHours: 100,
    field: 'Образование',
    eduField: 'humanities',
    eduLevel: 2,
    proSkills: 1,
    network: 2,
    expenses: 32000,
    familySize: 1,
    habits: [],
    hasCar: false,
    dreamOptions: ['lakehouse', 'school', 'fund'],
  },
  {
    id: 'marina',
    name: 'Марина',
    age: 29,
    blurb: 'Врач: доход высокий, времени мало.',
    difficulty: 'normal',
    cash: 220000,
    timePerMonth: 225,
    jobTitle: 'Врач',
    careerLevel: 3,
    salary: 110000,
    jobHours: 130,
    field: 'Медицина',
    eduField: 'tech',
    eduLevel: 3,
    proSkills: 2,
    network: 2,
    expenses: 48000,
    familySize: 0,
    habits: [{ id: 'coffee', name: 'Кофейня', monthlyCost: 4000, monthlyTime: 4 }],
    hasCar: true,
    dreamOptions: ['worldtrip', 'lakehouse', 'yacht'],
  },
  {
    id: 'timur',
    name: 'Тимур',
    age: 27,
    blurb: 'Мастер на час, тянет к своему делу.',
    difficulty: 'easy',
    cash: 90000,
    timePerMonth: 225,
    jobTitle: 'Мастер',
    careerLevel: 2,
    salary: 48000,
    jobHours: 85,
    field: 'Ремонт',
    eduField: 'tech',
    eduLevel: 1,
    proSkills: 2,
    network: 2,
    expenses: 26000,
    familySize: 0,
    habits: [],
    hasCar: true,
    dreamOptions: ['service', 'studio', 'farm'],
  },
  {
    id: 'olga',
    name: 'Ольга',
    age: 31,
    blurb: 'Менеджер проектов в IT.',
    difficulty: 'normal',
    cash: 310000,
    timePerMonth: 225,
    jobTitle: 'Проект-менеджер',
    careerLevel: 3,
    salary: 140000,
    jobHours: 120,
    field: 'IT',
    eduField: 'tech',
    eduLevel: 2,
    proSkills: 3,
    network: 3,
    expenses: 62000,
    familySize: 1,
    habits: [{ id: 'smoke', name: 'Курение', monthlyCost: 5000, monthlyTime: 8 }],
    hasCar: false,
    dreamOptions: ['sportscar', 'worldtrip', 'studio'],
  },
  {
    id: 'sergey',
    name: 'Сергей',
    age: 41,
    blurb: 'Супервайзер с семьёй и кредитом привычек.',
    difficulty: 'hard',
    cash: 85000,
    timePerMonth: 225,
    jobTitle: 'Супервайзер',
    careerLevel: 3,
    salary: 78000,
    jobHours: 115,
    field: 'Ритейл',
    eduField: 'econ',
    eduLevel: 1,
    proSkills: 2,
    network: 2,
    expenses: 55000,
    familySize: 3,
    habits: [{ id: 'lottery', name: 'Лотереи', monthlyCost: 3000, monthlyTime: 3 }],
    hasCar: true,
    dreamOptions: ['lakehouse', 'fund', 'service'],
  },
  {
    id: 'daria',
    name: 'Дарья',
    age: 25,
    blurb: 'Выпускница экономист, старт карьеры.',
    difficulty: 'normal',
    cash: 60000,
    timePerMonth: 225,
    jobTitle: 'Аналитик-джун',
    careerLevel: 1,
    salary: 55000,
    jobHours: 100,
    field: 'Финансы',
    eduField: 'econ',
    eduLevel: 2,
    proSkills: 1,
    network: 1,
    expenses: 28000,
    familySize: 0,
    habits: [],
    hasCar: false,
    dreamOptions: ['gallery', 'worldtrip', 'fund'],
  },
  {
    id: 'pavel',
    name: 'Павел',
    age: 38,
    blurb: 'Риэлтор: связи уже есть.',
    difficulty: 'normal',
    cash: 190000,
    timePerMonth: 225,
    jobTitle: 'Риэлтор',
    careerLevel: 3,
    salary: 70000,
    jobHours: 95,
    field: 'Недвижимость',
    eduField: 'econ',
    eduLevel: 1,
    proSkills: 2,
    network: 5,
    expenses: 45000,
    familySize: 2,
    habits: [],
    hasCar: true,
    dreamOptions: ['yacht', 'lakehouse', 'gallery'],
  },
  {
    id: 'lena',
    name: 'Елена',
    age: 45,
    blurb: 'Бухгалтер с опытом и осторожностью.',
    difficulty: 'easy',
    cash: 420000,
    timePerMonth: 225,
    jobTitle: 'Главный бухгалтер',
    careerLevel: 4,
    salary: 95000,
    jobHours: 110,
    field: 'Учёт',
    eduField: 'econ',
    eduLevel: 3,
    proSkills: 3,
    network: 2,
    expenses: 50000,
    familySize: 2,
    habits: [],
    hasCar: true,
    dreamOptions: ['farm', 'fund', 'school'],
  },
  {
    id: 'nikita',
    name: 'Никита',
    age: 24,
    blurb: 'Курьер мечтает о медиа.',
    difficulty: 'hard',
    cash: 25000,
    timePerMonth: 225,
    jobTitle: 'Курьер',
    careerLevel: 1,
    salary: 35000,
    jobHours: 110,
    field: 'Логистика',
    eduField: 'none',
    eduLevel: 0,
    proSkills: 0,
    network: 1,
    expenses: 22000,
    familySize: 0,
    habits: [{ id: 'games', name: 'Игры', monthlyCost: 2000, monthlyTime: 20 }],
    hasCar: false,
    dreamOptions: ['studio', 'sportscar', 'worldtrip'],
  },
  {
    id: 'vera',
    name: 'Вера',
    age: 36,
    blurb: 'Маркетолог, сильна в продвижении.',
    difficulty: 'normal',
    cash: 250000,
    timePerMonth: 225,
    jobTitle: 'Маркетолог',
    careerLevel: 3,
    salary: 120000,
    jobHours: 105,
    field: 'Маркетинг',
    eduField: 'humanities',
    eduLevel: 2,
    proSkills: 4,
    network: 4,
    expenses: 58000,
    familySize: 1,
    habits: [],
    hasCar: false,
    dreamOptions: ['gallery', 'studio', 'yacht'],
  },
  {
    id: 'anton',
    name: 'Антон',
    age: 33,
    blurb: 'Инженер на заводе.',
    difficulty: 'normal',
    cash: 170000,
    timePerMonth: 225,
    jobTitle: 'Инженер',
    careerLevel: 3,
    salary: 90000,
    jobHours: 120,
    field: 'Производство',
    eduField: 'tech',
    eduLevel: 3,
    proSkills: 2,
    network: 1,
    expenses: 40000,
    familySize: 2,
    habits: [{ id: 'beer', name: 'Вечерний бар', monthlyCost: 6000, monthlyTime: 10 }],
    hasCar: true,
    dreamOptions: ['service', 'lakehouse', 'farm'],
  },
  {
    id: 'sofia',
    name: 'София',
    age: 28,
    blurb: 'HR-специалист, много контактов.',
    difficulty: 'easy',
    cash: 160000,
    timePerMonth: 225,
    jobTitle: 'HR',
    careerLevel: 2,
    salary: 75000,
    jobHours: 95,
    field: 'HR',
    eduField: 'humanities',
    eduLevel: 2,
    proSkills: 2,
    network: 4,
    expenses: 36000,
    familySize: 0,
    habits: [],
    hasCar: false,
    dreamOptions: ['worldtrip', 'fund', 'school'],
  },
  {
    id: 'roman',
    name: 'Роман',
    age: 48,
    blurb: 'Малый бизнесмен на грани выгорания.',
    difficulty: 'hard',
    cash: 50000,
    timePerMonth: 225,
    jobTitle: 'Владелец лавки',
    careerLevel: 2,
    salary: 40000,
    jobHours: 140,
    field: 'Торговля',
    eduField: 'econ',
    eduLevel: 1,
    proSkills: 3,
    network: 3,
    expenses: 70000,
    familySize: 3,
    habits: [{ id: 'smoke', name: 'Курение', monthlyCost: 5000, monthlyTime: 8 }],
    hasCar: true,
    dreamOptions: ['yacht', 'fund', 'gallery'],
  },
  {
    id: 'kira',
    name: 'Кира',
    age: 26,
    blurb: 'Дизайнер на фриланс-стыке с наймом.',
    difficulty: 'normal',
    cash: 110000,
    timePerMonth: 225,
    jobTitle: 'Дизайнер',
    careerLevel: 2,
    salary: 80000,
    jobHours: 100,
    field: 'Дизайн',
    eduField: 'humanities',
    eduLevel: 2,
    proSkills: 3,
    network: 2,
    expenses: 38000,
    familySize: 0,
    habits: [{ id: 'net', name: 'Соцсети', monthlyCost: 0, monthlyTime: 15 }],
    hasCar: false,
    dreamOptions: ['studio', 'gallery', 'worldtrip'],
  },
  {
    id: 'gleb',
    name: 'Глеб',
    age: 52,
    blurb: 'Эксперт-режим: мало времени до пенсии.',
    difficulty: 'expert',
    cash: 300000,
    timePerMonth: 225,
    jobTitle: 'Директор смены',
    careerLevel: 4,
    salary: 130000,
    jobHours: 125,
    field: 'Логистика',
    eduField: 'tech',
    eduLevel: 2,
    proSkills: 3,
    network: 2,
    expenses: 80000,
    familySize: 2,
    habits: [{ id: 'lottery', name: 'Лотереи', monthlyCost: 4000, monthlyTime: 4 }],
    hasCar: true,
    dreamOptions: ['yacht', 'school', 'fund'],
  },
]
